# Generated by Django 4.2.2 on 2023-06-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='my_user_table',
        ),
    ]
